<a href="https://colab.research.google.com/github/tompickering-aur/Practice/blob/main/notebooks/02_Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 2: Python & NumPy for Data Analysis

**Session objectives**
1. Learn the Python building blocks you'll use throughout the course
2. Understand NumPy arrays and why they matter for data analysis
3. Apply these tools to a real Airbnb dataset

---
# 1. Python Essentials



## 1.1 Python Packages

When you start a new kernel, only a core set of Python resources is initially available. You'll need to import additional packages for most data science tasks, as these core resources are intentionally kept minimal. These extra resources come in **packages**, which themselves are split into different **modules**. Python can be extended by more than 200,000 packages. Some large packages, like scikit-learn, are collections of modules called **subpackages**.

For example, if you need to calculate the square root of 2, you would import the `math` package, which includes various mathematical functions. Once imported, all its functions become available. The notation `math.sqrt` indicates that `sqrt` is a function from the `math` package.

NumPy will be our main tool today, let's import it and call it np

In [1]:
import numpy as np

To use a function within numpy, you can use `np.array` indicates that `array` is a function from the `np` package.

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Most packages used in this course (NumPy, pandas, matplotlib) are pre-installed in Anaconda and Google Colab. If you ever need something extra, run `pip install packagename` in a terminal, or `!pip install packagename` inside a notebook cell.

## 1.2 Variables and types

Python infers the **type** of a variable automatically. The types you'll encounter most are `int`, `float`, `bool`, and `str`. Use `type()` to check.

In [ ]:
revenue     = 4_200_000   # int   — annual revenue in €
margin      = 0.32        # float — gross margin
is_listed   = True        # bool  — publicly listed company
company     = 'Inditex'   # str - text

type(revenue)

int

> ✅ **Sanity check:** Use the ``type`` command to check your values as you go. A lot of silent mistakes can happen due to something being coded as the wrong type.
>
> A few examples:
> - integers will truncate numbers (use float instead)
> - strings used as numbers
> - Boolean (true/false) stored as string or number

In [ ]:
int(2.9)

2

In [ ]:
# in general only the last line of code will be printed below your cell
type(margin)
type(company)

# but you can use the print command enables us to see return more information
print(type(revenue), type(margin), type(is_listed), type(company))

<class 'int'> <class 'float'> <class 'bool'> <class 'str'>


> ✅ **Sanity check:** Use the ``print`` command to check what the code does, we will include many ways to include it in this course.

You can reassigning a variable replaces its previous value:

In [ ]:
margin = margin * 1.05   # margins improved by 5%
margin

0.336

**Booleans** arise naturally from comparisons, and behave as `1` / `0` in arithmetic — useful for counting:

In [ ]:
profitable = margin > 0.30
print(profitable)          # True
print(int(profitable))     # 1

True
1


## 1.3 Data containers



### Lists

A **list** holds an ordered sequence of items (any mix of types). You'll mainly use lists as a stepping stone before loading data into NumPy or pandas.

In [ ]:
# Quarterly revenues for a retailer (€ millions)
quarterly = [8.2, 9.5, 11.3, 14.7]

print(quarterly[0])     # first element — Python indexes from 0
print(quarterly[-1])    # last element
print(quarterly[1:3])   # slice: Q2 and Q3 (index 3 is excluded)

8.2
14.7
[9.5, 11.3]


In [ ]:
# you can find the length of the list easily
len(quarterly)

4

> ✅ **Sanity check:** You can use ``len`` for many python objects (lists, arrays, dictionaries,..) to see how many items you have. For 2D objects, you can use ``shape``

Lists feel intuitive, but watch what happens when you try to do maths on them:

In [ ]:
print('List * 2 :', quarterly * 2)   # repeats the list — not what you want!

List * 2 : [8.2, 9.5, 11.3, 14.7, 8.2, 9.5, 11.3, 14.7]


### Arrays

Instead, the numpy package does two things for us:
1. keep everything inside the list the same type
2. easy to apply functions and computations across the values

In [ ]:
# first we switch the list to make it a numpy array
arr = np.array(quarterly)
print(arr)

# the type of the array is `array`
type(arr)

# the type of its elements
arr.dtype

[ 8.2  9.5 11.3 14.7]


dtype('float64')

> ✅ **Sanity check:** ``.dtype`` shows you the type inside the array

In [ ]:
# what happens when we add a string?
quarterly_mixed = np.array([8.2, 9.5, 'Q3-restatement', 14.7])
print(quarterly_mixed)
quarterly_mixed.dtype

['8.2' '9.5' 'Q3-restatement' '14.7']


dtype('<U32')

In [ ]:
# Here we can double the values or apply a growht easily
print('Array * 2:', arr * 2)         # doubles every value
print('YoY growth:', arr * 1.08)     # apply 8% growth to all quarters

Array * 2: [16.4 19.  22.6 29.4]
YoY growth: [ 8.856 10.26  12.204 15.876]


**Step intervals** can be used if we need to select only every n-th element of the array:

In [ ]:
arr, arr[::2]

(array([ 8.2,  9.5, 11.3, 14.7]), array([ 8.2, 11.3]))

One special case of this which is used quite often is to use steps of -1, which is equivalent to reversing the array.

In [ ]:
arr, arr[::-1]

(array([ 8.2,  9.5, 11.3, 14.7]), array([14.7, 11.3,  9.5,  8.2]))

### Dictionaries

A **dictionary** maps keys to values. It is a natural fit for a single record (customer, product, transaction).

For example, the following dictionary contains five features of a customer:

In [ ]:
customer = {
    'id': 'C-8821',
    'segment': 'Premium',
    'lifetime_value': 4320,
    'purchases': 17,
    'active': True
}

# The keys can be listed and we access the values by using the keys
print(customer.keys())
print(customer['segment'])   # access by key

dict_keys(['id', 'segment', 'lifetime_value', 'purchases', 'active'])
Premium


In [ ]:
len(customer)

5

**Example**

Dictionaries are important because a lot of real life data comes in the form of dictionaries. Let's say you want to get the latests information on bitcoin. You may want to call the [CoinGecko](http://coingecko.com) API (Application Programming Interface) to obtain that data.

Typically, these API's are essentially just websites that you visit. In this case:

https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en

In [ ]:
import requests

api_url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en'
data = requests.get(api_url).json()[0]

data

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
 'current_price': 62254,
 'market_cap': 1247422545218,
 'market_cap_rank': 1,
 'fully_diluted_valuation': 1247422545218,
 'total_volume': 30889430529,
 'high_24h': 62800,
 'low_24h': 60423,
 'price_change_24h': 1634.46,
 'price_change_percentage_24h': 2.69625,
 'market_cap_change_24h': 31183648359,
 'market_cap_change_percentage_24h': 2.56394,
 'circulating_supply': 20039087.0,
 'total_supply': 20039087.0,
 'max_supply': 21000000.0,
 'ath': 126080,
 'ath_change_percentage': -50.62314,
 'ath_date': '2025-10-06T18:57:42.558Z',
 'atl': 67.81,
 'atl_change_percentage': 91708.3068,
 'atl_date': '2013-07-06T00:00:00.000Z',
 'roi': None,
 'last_updated': '2026-06-07T17:23:00.974Z'}

## 1.4 Functions

Many functions are provided within the packages you will use. For example, the `math` package provides mathematical functions:

In [ ]:
import math
math.log(revenue)    # natural log of annual revenue

15.250595083253597

You can also write your own **function** to reuse in your notebook.

Key elements in a function:
1. You define the function and include names for the arguments you want to input.
2. You indent your code and write down a series of actions to be taken upon the arguments.
3. You specify what you want your funciton to `return' (still indented)

In [ ]:
# we define a function f with argument x which will return y (1/(1-x^2))
def f(x):
    y = 1/(1 - x**2)
    return y
# python will check the general syntax (parentheses, commas, etc.)

# we apply it to 2
f(2)

-0.3333333333333333

In [ ]:
# Look what happens if we apply it to something that doesn't make sense
f(1)

ZeroDivisionError: division by zero

In [ ]:
f('Mary')

Example of a longer function,

In [ ]:
def gross_profit(revenue, cost):
    """Returns gross profit and margin."""
    profit = revenue - cost
    margin = profit / revenue
    return profit, margin   # functions can return multiple values

gross_profit(500_000, 320_000)

Short, single-expression functions can be written as **lambda functions**. Let's calculate the Compound Annual Growth Rate.

In [ ]:
cagr = lambda start, end, years: (end / start) ** (1 / years) - 1
cagr(100, 160, 5) # # ~9.9% per year

## 1.5 Loops and list comprehensions

In data analysis you'll use loops mainly to build lists before converting them to arrays. The compact form is a **list comprehension**:

In [ ]:
regions = ['North', 'South', 'North', 'West', 'South']

# Flag Northern region entries
is_north = [1 if r == 'North' else 0 for r in regions]
print(is_north)

Loops are much less frequent in the data science practice, because NumPy and Pandas provide **vectorized functions**, that, when applied to a data container such as a Pandas series, return a data container with same shape, whose terms are the values of the function on the corresponding terms of the original data container. Nevertheless, we may use occasionally a `for` loop in this course.  

Also ubiquitous in programming is **conditional logic**, operationalized through **if-then-else** commands. You also have this in Python. For instance, if you wish to create a dummy flag for names with more than 5 letters in the list `mylist`, you can do it with:

In [ ]:
flaglist = [1 if len(name) > 4 else 0 for name in regions]
flaglist

[1, 1, 1, 0, 1]

> ## ✏️  You try it
>
>a) Create a phone book using a `dict` where you have 5 names of your friends as a key and their phone number as the values.
>
>b) Then, also create a reverse mapping so that you can find out who's calling you based on the number.
>
>b) Define a function called `find_caller_id` that returns the name of the person who's calling you based on the number, use the reverse mapping.
>
> *Feel free to use AI for the code but keep it simple! Ask AI to just use basic packages and numpy. Then, analyze the code and check that you understand what it is doing. *

# 2. Data analysis with basic Python and Numpy

## 2.1 2D arrays and shape

A 2D array is a matrix — rows are observations, columns are variables. Here each row is a sales representative and the columns are `[calls_made, deals_closed, revenue_k€]`:

In [ ]:
# rows = sales reps, cols = [calls_made, deals_closed, revenue (k€)]
sales_reps = np.array([
    [120,  8, 42],
    [ 95, 11, 61],
    [140,  6, 28],
    [ 80, 14, 74],
    [110,  9, 48],
    [130,  7, 35],
])

print('shape:', sales_reps.shape)   # (rows, columns)

The number of terms in each rows and columns are the **dimensions** of that axis. The dimensions are collected in the attribute `shape`:


In [ ]:
sales_reps.shape


`shape` returns a **tuple** — a fixed, immutable sequence (cannot be changed). You'll see it everywhere once you start working with data.

> ✅ **Sanity check:** Like ``len``, ``shape`` is extremely useful to keep track of how many rows (observations) and columns (variables) you have.

## 2.2 Summary statistics

Use `axis=0` to compute across rows (one result per column), `axis=1` to compute across columns (one result per row):

In [ ]:
# Average calls, deals, and revenue across all reps
np.mean(sales_reps, axis=0)

In [ ]:
# Best performer in each category
np.max(sales_reps, axis=0)

In [ ]:
# other useful commands
np.median(sales_reps, axis=0)
np.std(sales_reps, axis=0)

> ✅ **Sanity check:** Does the mean, median, and standard deviation look reasonable given your data? Think of your expected range and average and if there might be any issues with the coding.

**DEMO**: Play around with this simulation to get a feeling for how it works.

<center>
  <a href='https://claude.ai/public/artifacts/7a188c7b-8186-4188-a0cc-ec4c60e66922' target="_blank">
    <img src='https://raw.githubusercontent.com/ciri/iese-dsfb/main/images/demo.png'>
  </a>
</center>


## 2.3 Indexing and slicing

For 2D arrays: `arr[row, col]`. Use `:` to select all rows or all columns.

In [ ]:
print(sales_reps[0])       # first rep — all features
print(sales_reps[0, [1,2]])    # deals and revenue of first rep
print(sales_reps[:, 1])    # deals_closed column for all reps
print(sales_reps[:3])      # first 3 reps

In [ ]:
# Select specific reps by index
sales_reps[[1, 3], :]

In [ ]:
# Focus on revenue column (index 2) and do calculations
revenue = sales_reps[:, 2]

# we can use print to show what we are returning
print('25th / 75th pct:', np.percentile(revenue, 25), '/', np.percentile(revenue, 75))

> ✅ **Sanity check:** Check the first 5 items to see how it looks with ``print(sales_reps[:5])``

**DEMO**: You can test your indexing knowledge here:
<center>
  <a href='https://claude.ai/public/artifacts/97b2f0ad-9bc7-47fb-99ab-512f71844cbc' target="_blank">
    <img src='https://raw.githubusercontent.com/ciri/iese-dsfb/main/images/demo.png'>
  </a>
</center>

## 2.4 Boolean filtering

One of the most powerful tools in data analysis: selecting rows that satisfy a condition.

In [ ]:
# select the 0 and 2nd columns of sales_reps
calls   = sales_reps[:, 0]
revenue = sales_reps[:, 2]
print('size revenue:', len(revenue))

# Boolean mask — one True/False per rep
high_revenue = revenue > 50
print('High-revenue reps mask:', high_revenue)

# Apply mask to original data
revenue[high_revenue]
print('Revenue of top performers:', revenue[high_revenue])

# Combine conditions: high revenue but not many calls (efficient reps)
efficient = (revenue > 50) & (calls < 110)
print('Efficient reps:')
print(sales_reps[efficient])

size revenue: 6
High-revenue reps mask: [False  True False  True False False]
Revenue of top performers: [61 74]
Efficient reps:
[[95 11 61]
 [80 14 74]]


## 2.5 Sorting and ranking

`np.argsort` returns the *indices* that would sort an array, very useful for top-N rankings.

In [ ]:
sort_idx = np.argsort(revenue)   # low to high

top3_idx = sort_idx[-3:][::-1]   # last 3, reversed = top 3
print('Top 3 reps by revenue:')
print(sales_reps[top3_idx])

Top 3 reps by revenue:
[[ 80  14  74]
 [ 95  11  61]
 [110   9  48]]


> ✅ **Sanity check:** Check the outliers of your data, are they errors or do they make sense? Should they be recoded?

## 2.6 Vectorized functions

Functions written with NumPy operations work element-wise on entire arrays (no loops needed!). Here is the classic example: BMI from a population health dataset.

In [ ]:
# rows = employees at a corporate wellness check, cols = [height_cm, weight_kg]
employees = np.array([
    [160, 55], [175, 70], [155, 52], [180, 77],
    [165, 58], [170, 68], [162, 54], [178, 75],
    [158, 53], [172, 72]
])


def calc_bmi(h_cm, w_kg):
    return w_kg / (h_cm / 100) ** 2

# we apply the calc_bmi function to:
# height (column index 0) and
# weight (column index 1)
bmi = calc_bmi(employees[:, 0], employees[:, 1])
print("type bmi:", bmi.dtype)

# Show the bmi for each employee and the average BMI
print('BMI per employee:', np.round(bmi, 1))
print('Average BMI     :', np.mean(bmi).round(1))

type bmi: float64
BMI per employee: [21.5 22.9 21.6 23.8 21.3 23.5 20.6 23.7 21.2 24.3]
Average BMI     : 22.4


> ## ✏️ You try it — RFM customer scoring
>
>Let's perform RFM (Recency, Frequency, Monetary) analysis - a key technique in customer segmentation and marketing analytics.
>
>RFM analysis is a behavior-based technique used to segment customers by examining their transaction history. It evaluates customers based on three dimensions:
>
>- **Recency (R)**: How recently a customer has made a purchase.
>- **Frequency (F)**: How often a customer makes a purchase.
>- **Monetary Value (M)**: How much money a customer spends on purchases.
>
>The idea of this battle-tested technique is that it allows us to (a) categorize customers into distinct groups for targeted marketing (b) find out recent / frequent buyers which are more likely to respond to new offers (c) focus efforts on segments that are more likely to generate higher returns.
>
>Let's start with generating the dataset (you don't need to worry about this code for now).

In [ ]:
import numpy as np

def generate_rfm_aggregate_data(num_customers=100, max_days_since_last_purchase=365, max_frequency=25, max_monetary=10000):
    """
    Generate synthetic aggregate RFM data for customers.

    Parameters:
    - num_customers: int, number of unique customers.
    - max_days_since_last_purchase: int, maximum number of days since the last purchase.
    - max_frequency: int, maximum number of transactions made by a customer.
    - max_monetary: int, maximum total amount spent by a customer.

    Returns:
    - data: np.ndarray, 2D array with columns: CustomerID, Recency, Frequency, Monetary.
    """
    np.random.seed(42)  # For reproducibility

    # I use random numbers here for the sake of example, this is an artificial dataset
    recency   = np.round(np.random.randint(1, max_days_since_last_purchase + 1, num_customers),2)
    frequency = np.round(np.random.randint(1, max_frequency + 1, num_customers),2)
    monetary  = np.round(np.random.uniform(10.0, max_monetary, num_customers), 2)

    # Combining all three to output 1 matrix
    data = np.column_stack((recency, frequency, monetary))

    return data

rfm_data = generate_rfm_aggregate_data(num_customers=10000)

rfm_data

array([[1.03000e+02, 1.80000e+01, 7.29780e+03],
       [3.49000e+02, 1.20000e+01, 2.07865e+03],
       [2.71000e+02, 1.60000e+01, 3.77658e+03],
       ...,
       [3.64000e+02, 9.00000e+00, 4.75868e+03],
       [1.40000e+02, 1.30000e+01, 7.37955e+03],
       [1.90000e+02, 3.00000e+00, 2.01410e+02]], shape=(10000, 3))

> 1. Create a function `rfm_score` that computes a simple RFM score:
>    
>    Score = (max_recency - recency) + frequency + (monetary / 1000)
>
>Higher is better.
>
> 2. Find top 5 customers with the highest scores.

In [ ]:
# 1. Compute RFM scores for all customers.
rfm_data = generate_rfm_aggregate_data(num_customers=1000)

def rfm_score(data):

    return ...


scores = ...

In [ ]:
# 2. Find top 5 customers with the highest scores.
top5_idx = ...


top5_scores = ....


print("Top 5 customers (indices):", top5_idx)
print("Top 5 scores:", top5_scores)

SyntaxError: invalid syntax (2172785753.py, line 5)

# 3. Checking your code with AI

You are encouraged to use Gemini, ChatGPT, Claude, or similar tools. However, you should be careful to keep your coding simple to understand what AI is doing and avoid little mistakes.

Five prompting patterns that work well:

### Pattern 1 — Don't run all the code at once: run cell by cell and run your own sanity checks in between

> *See the ideas for sanity checks in all the notebooks marked with ✅*

### Pattern 2 — Show your data, ask something specific

> *I have a NumPy array called `prices` with nightly Airbnb prices. Some values are 0 (likely errors). How do I replace them with `np.nan` and compute the mean ignoring those values?*

### Pattern 3 — Specific packages and output needed

> *Could you use the panda package to combine the datasets into on dataframe*

### Pattern 4 — Ask for an explanation, not just code

> *Explain what `np.percentile(arr, 75)` does and when I would use it in a pricing analysis.*

### Pattern 5 — Ask AI to do it's own sanity checks

> *Check that the sample size is still the same and include a print statement verifying the results*


### What to watch out for
- AI tools sometimes import packages they don't use (e.g., importing `re` without ever calling it)
- They may use functions we haven't covered — that's fine, but **justify the choice** in your notebook
- Don't use AI for the **ideation phase** of the Airbnb assignment — the hypothesis should be yours

---
> ## 🅰️ 4. Preview: Your Airbnb Dataset
>
>**Part 1** Download your city's `listings.csv` from [insideairbnb.com](https://insideairbnb.com/) and place it in the appropriate folder. We'll use Python's built-in `csv` module to peek at the structure before we have pandas available.

In [ ]:
import csv

with open('data_raw/listings.csv', encoding='utf-8') as f:
    reader = csv.reader(f)
    headers = next(reader)
    rows = [next(reader) for _ in range(3)]

# number of columns (variables)
len(headers)

79

In [ ]:
#name of the columns
headers[:10]

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id']

>**Part 2** Narrow down your hypotheses. Look at Airbnb's data dictionary and think about what hypotheses you can actually measure for your project.
>
>[Inside Airbnb data dictionary](https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4)

>**Extension** Ask AI to use pandas to load the dataset and explore the distribution of the variables that interest you.

---
## What's next

Tomorrow we introduce **pandas**, which gives every column a name, handles mixed types, and makes the data cleaning we previewed today trivial. Everything you learned today — indexing, boolean filtering, summary statistics — carries directly over. You'll use it to load, clean, and explore the full Airbnb dataset for your assignment.

### References
This notebook is based on an original version by Miguel Ángel Canela (2022) and Enric Junqué de Fortuny (2025).

## Additional Resources

There are many books for learning about Python, but some of them would not be appropriate for learning how to work with data in Python. It can even happen that you do not find anything about data in many of them. Mind that Python has so many applications that the intersection of the know-how of all Python users is relatively narrow. For an introduction to Python as a programming language, in a computer science context, I would recommend Zelle (2010). For the self-learning data scientist, McKinney (2017) and VanderPlas (2017) are both worth their price.

There is also plenty of learning materials in Internet, including MOOC's. For instance, **Coursera** has a pack of courses on Python (see `coursera.org/courses?query=python`). But, probably, the most attractive marketplace for data science courses is **DataCamp**. They offer, under subscription or academic license, an impressive collection of courses, most of them focused on either R or Python. In addition to follow DataCamp courses, you can also benefit from the **DataCamp Community Tutorials**, which are free and cover a wide range of topics. Finally, a good place to start is [CS dojo](https://www.youtube.com/watch?v=Z1Yd7upQsXY&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg&index=1).

For Numpy, you can check out this introductory tutorial: [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html)


# Solutions

> ## ✏️  You try it
>
>a) Create a phone book using a `dict` where you have 5 names of your friends as a key and their phone number as the values.
>
>b) Then, also create a reverse mapping so that you can find out who's calling you based on the number.
>
>c) Define a function called `find_caller_id` that returns the name of the person who's calling you based on the number, use the reverse mapping.

In [ ]:
# a) Phone book dictionary
phone_book = {
    "Alice":   "612 345 678",
    "Bob":     "623 456 789",
    "Carmen":  "634 567 890",
    "David":   "645 678 901",
    "Elena":   "656 789 012"
}

type(phone_book)


dict

In [ ]:
# b) Reverse mapping (number → name)
reverse_mapping = {number: name for name, number in phone_book.items()}

reverse_mapping

{'612 345 678': 'Alice',
 '623 456 789': 'Bob',
 '634 567 890': 'Carmen',
 '645 678 901': 'David',
 '656 789 012': 'Elena'}

In [ ]:
# c) find_caller_id function
def find_caller_id(number):
    return reverse_mapping[number]

In [ ]:
# --- Test it ---
print(find_caller_id("634 567 890"))

Carmen


In [ ]:
def find_caller_id(number):
    if number in reverse_mapping:
        return reverse_mapping[number]
    else:
        return "Unknown number"

In [ ]:
print(find_caller_id("634 567 891"))

Unknown number


> ## ✏️ You try it Worked example — RFM customer scoring
>
>Let's perform RFM (Recency, Frequency, Monetary) analysis - a key technique in customer segmentation and marketing analytics.
>
>RFM analysis is a behavior-based technique used to segment customers by examining their transaction history. It evaluates customers based on three dimensions:
>
>- **Recency (R)**: How recently a customer has made a purchase.
>- **Frequency (F)**: How often a customer makes a purchase.
>- **Monetary Value (M)**: How much money a customer spends on purchases.
>
>The idea of this battle-tested technique is that it allows us to (a) categorize customers into distinct groups for targeted marketing (b) find out recent / frequent buyers which are more likely to respond to new offers (c) focus efforts on segments that are more likely to generate higher returns.
>
>Let's start with generating the dataset (you don't need to worry about this code for now).
>Create a function `rfm_score` that computes a simple RFM score:
>    
>    Score = (max_recency - recency) + frequency + (monetary / 1000)
>
>Higher is better.

In [ ]:
## 1. Compute RFM scores for all customers.
rfm_data = generate_rfm_aggregate_data(num_customers=1000)

def rfm_score(data):
    score = (np.max(data[:, 0]) - data[:, 0]) + data[:, 1] + (data[:, 2] / 1000)
    return np.round(score)

scores = rfm_score(rfm_data)

# 2. Find top 5 customers with the highest scores.
top5_idx = np.argsort(scores)
sort_idx = np.argsort(scores)

top5_idx = sort_idx [-5:][::-1]
top5_scores = scores[top5_idx]

print("Top 5 customers (indices):", top5_idx)
print("Top 5 scores:", top5_scores)

Top 5 customers (indices): [895 446 613 842 648]
Top 5 scores: [394. 392. 391. 389. 389.]
